#
# Copyright (c) 2019-2020 Ruben Perez Hidalgo (rubenperez038 at gmail dot com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

__linux_addons_defaults: &__linux_addons_defaults
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
    packages:
      - boost1.70
      - python3
      - valgrind

__linux_defaults: &__linux_defaults
  os: linux
  dist: bionic
  sudo: true
  addons:
    <<: *__linux_addons_defaults
  script:
    - bash -e -x ci/build_unix.sh
    
__linux_mysql_defaults: &__linux_mysql_defaults
  <<: *__linux_defaults
  services:
    - mysql
    
__linux_mariadb_defaults: &__linux_mariadb_defaults
  <<: *__linux_defaults
  addons:
    <<: *__linux_addons_defaults
    mariadb: '10.3'

__osx_defaults: &__osx_defaults
  os: osx
  osx_image: xcode11.3
  sudo: true
  compiler: clang
  script:
    - bash -e -x ci/build_unix.sh
    
__osx_cmake_options: &__osx_cmake_options "CMAKE_OPTIONS=-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl"


language: cpp

matrix:
  include:
    - name: linux_gcc_x64_debug_mysql
      <<: *__linux_mysql_defaults
      compiler: gcc
      env:
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mysql
        - USE_VALGRIND=1
    - name: linux_gcc_x64_release_mysql
      <<: *__linux_mysql_defaults
      compiler: gcc
      env:
        - CMAKE_BUILD_TYPE=Release
        - DATABASE=mysql
    - name: linux_clang_x64_debug_mysql
      <<: *__linux_mysql_defaults
      compiler: clang
      env:
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mysql
        - USE_VALGRIND=1
    - name: linux_clang_x64_release_mysql
      <<: *__linux_mysql_defaults
      compiler: clang
      env:
        - CMAKE_BUILD_TYPE=Release
        - DATABASE=mysql
    - name: linux_gcc_x64_debug_mariadb
      <<: *__linux_mariadb_defaults
      compiler: gcc
      env:
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mariadb
        - USE_VALGRIND=1
    - name: linux_gcc_x64_release_mariadb
      <<: *__linux_mariadb_defaults
      compiler: gcc
      env:
        - CMAKE_BUILD_TYPE=Release
        - DATABASE=mariadb
    - name: linux_clang_x64_debug_mariadb
      <<: *__linux_mariadb_defaults
      compiler: clang
      env:
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mariadb
        - USE_VALGRIND=1
    - name: linux_clang_x64_release_mariadb
      <<: *__linux_mariadb_defaults
      compiler: clang
      env:
        - CMAKE_BUILD_TYPE=Release
        - DATABASE=mariadb
    - name: osx_clang_x64_debug_mysql
      <<: *__osx_defaults
      env:
        - *__osx_cmake_options
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mysql
    - name: osx_clang_x64_release_mysql
      <<: *__osx_defaults
      env:
        - *__osx_cmake_options
        - CMAKE_BUILD_TYPE=Release
        - DATABASE=mysql
    - name: osx_clang_x64_debug_mariadb
      <<: *__osx_defaults
      env:
        - *__osx_cmake_options
        - CMAKE_BUILD_TYPE=Debug
        - DATABASE=mariadb
    - name: osx_clang_x64_release_mariadb
      <<: *__osx_defaults
      env:
        - *__osx_cmake_options
        - CMAKE_BUILD_TYPE=Release
        - DATABASE=mariadb
